[graph]
all-features = true

[bans]
multiple-versions = "deny"
wildcards = "deny"

deny = [
  { crate = "openssl", use-instead = "rustls" },
  { crate = "openss-sys", use-instead = "rustls" },
]

skip = [
  { crate = "nb@<1.1.0", reason = "nb@1.1.0 still requires nb@0.1.3" },
]

[licenses]
allow = ["Apache-2.0", "MIT", "Unicode-3.0"]

private = { ignore = true }
